# Generated by Django 5.2.10 on 2026-01-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
      
    ]
